### ISSUE TITLE
`--server` parameter not working

### ISSUE THREAD

**Issue by rawkode** [ashleydw/abao#4]
Even though I pass `--server http://server:10000`, it then tries to use a combination of `baseUrl` and my `--server` parameter.

```
  12) POST /create -> 400 Validate response code and body:
     Uncaught AssertionError: Got unexpected response code:
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Phoenix.Router.NoRouteError at POST /:80my-remote-server.com/create</title>

```

**Comment by ashleydw** [comment]
I think you're getting this error: https://github.com/cybertk/abao/issues/180

To be honest, this fork works but it's quite flakey, if you find errors you're welcome to PR them but I don't plan on spending too much time maintaining it. 

You may be better off following this thread: https://github.com/cybertk/abao/issues/57
